/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EntryPoint__factory>
getContractFactory(name: 'GhostWallet', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GhostWallet__factory>
getContractFactory(name: 'GhostFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GhostFactory__factory>

  getContractAt(name: 'EntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EntryPoint>
getContractAt(name: 'GhostWallet', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GhostWallet>
getContractAt(name: 'GhostFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GhostFactory>

  deployContract(name: 'EntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPoint>
deployContract(name: 'GhostWallet', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GhostWallet>
deployContract(name: 'GhostFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GhostFactory>

  deployContract(name: 'EntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPoint>
deployContract(name: 'GhostWallet', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GhostWallet>
deployContract(name: 'GhostFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GhostFactory>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  