/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface GhostFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createGhost"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GhostCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createGhost', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createGhost', data: BytesLike): Result;
  }

  
    export namespace GhostCreatedEvent {
      export type InputTuple = [wallet: AddressLike, owner: AddressLike];
      export type OutputTuple = [wallet: string, owner: string];
      export interface OutputObject {wallet: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GhostFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): GhostFactory;
    waitForDeployment(): Promise<this>;

    interface: GhostFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createGhost: TypedContractMethod<
      [owner: AddressLike, entryPoint: AddressLike, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createGhost'): TypedContractMethod<
      [owner: AddressLike, entryPoint: AddressLike, ],
      [string],
      'nonpayable'
    >;

    getEvent(key: 'GhostCreated'): TypedContractEvent<GhostCreatedEvent.InputTuple, GhostCreatedEvent.OutputTuple, GhostCreatedEvent.OutputObject>;

    filters: {
      
      'GhostCreated(address,address)': TypedContractEvent<GhostCreatedEvent.InputTuple, GhostCreatedEvent.OutputTuple, GhostCreatedEvent.OutputObject>;
      GhostCreated: TypedContractEvent<GhostCreatedEvent.InputTuple, GhostCreatedEvent.OutputTuple, GhostCreatedEvent.OutputObject>;
    
    };
  }